# Generated by Django 4.0.6 on 2022-11-25 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_ID', models.CharField(max_length=500)),
                ('booking_code', models.CharField(max_length=200)),
                ('odds', models.IntegerField(default=0)),
                ('remarks', models.CharField(choices=[('safe', 'safe'), ('risky', 'risky'), ('very risky', 'very risky')], max_length=20)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_ID', models.CharField(max_length=500)),
                ('booking_code', models.CharField(max_length=200)),
                ('odds', models.IntegerField(default=0)),
                ('remarks', models.CharField(max_length=20)),
            ],
        ),
    ]
