# Generated by Django 4.0.6 on 2022-11-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='odds',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
