# Generated by Django 4.0.6 on 2022-11-26 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_game_odds'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
